### ISSUE TITLE
buttons

### ISSUE THREAD

**Issue by Serzh812** [DenisD3D/Keys4Macros#2]
can I still add my own buttons ?
it is possible to change fixed day-night values ?

**Comment by DenisD3D** [comment]
You can actually add 3 custom command that can be executed with a key. They are called macro and can be set from the config menu of the mod (on the main menu > mods > select keys4gamemode > config button). You can then set your command that will be assigned by default to num pad 7, 8 and 9. Note that you will need one of the newest forge version in order to have access to the menu. Else you can edit the configuration file directly (in your .minecraft folder) 
Acctuallay you can't change the day night value while it's set to midnight and noon. But you can use the macro key as described before to set custom time set  command
Hope you will fine this helpful. If you need more information comment below or join my discord server (link on curseforge download page)
